### PR TITLE
Hunain/issue 12/settings

### PR DESCRIPTION
**Pull request by HunnySajid**
Related Task # https://github.com/roots-id/roots-react-native/issues/12

ChangeLog:
- Added settings screen
- Added developer screen link with dummy on settings
- Added save screen with mock data
- Implemented Picker Component to look better on IOS , previously it was not working with current styling

IOS
https://user-images.githubusercontent.com/19255438/197067056-0619cee2-609f-42c2-bc42-c0e9881f72a7.mov

Android

https://user-images.githubusercontent.com/19255438/197067392-d1cdbffe-18a1-47d1-b3e4-c4111144818c.mov

### CODE REVIEW

**Comment by 2byrds** [comment]
I had some trouble with this one @HunnySajid.
Web loaded fine. But android didn't load at all and iOS i wasn't able to click around.
I'll try to look into it a bit more tomorrow.
image

**Comment by HunnySajid** [comment]
> I had some trouble with this one @HunnySajid. Web loaded fine. But android didn't load at all and iOS i wasn't able to click around. I'll try to look into it a bit more tomorrow. image

@2byrds for ios its behavior is different. It provides a swapping up/down instead of showing a dropdown. 
Can you provide some details about android phone you are using so that I can look into it if it is os/mobile specific issue?

**Comment by 2byrds** [comment]
ah yes @HunnySajid I was able to swipe the picker on ios.  thx :)
image

**Comment by 2byrds** [comment]
I think my android emulator was in a bad state.  i started a fresh one and it worked great.
image

**Pull request merged**
