### PR TITLE
Remove auth flow add avatar in settings

### PR DESCRIPTION
**Pull request by HunnySajid**
Relevant Task: https://github.com/roots-id/roots-react-native/issues/22
- [x] Remove Auth Screens
- [x] Update user messages
- [x] Update Settings to set avatar/name/protected-pin
- [x] Change splash bg
- [x] Add icons in messages

### CODE REVIEW

**Comment by 2byrds** [comment]
image

image

image

**Review by 2byrds — CHANGES_REQUESTED** [review]
Great start @HunnySajid .  When I change my profile pic, I would like to see that reflected some where.  It didn't change my activity log icon.  I tried to click on the user icon but the profile didn't open on android and didn't open on ios (and not on web... although we might stop supporting web).  
I also couldn't send myself (in activity log) or send RootsID Discord a message, to see my new profile avatar and name reflected.

**Comment by HunnySajid** [comment]
@2byrds 
Check this out, i have covered following cases here.

- [x] When I change my profile pic, I would like to see that reflected some where. It didn't change my activity log icon
- [x] I also couldn't send myself (in activity log) or send RootsID Discord a message, to see my new profile avatar and name reflected.


https://user-images.githubusercontent.com/19255438/204910335-373783dc-4324-460a-8f85-5843d2a815a8.mov


However, I am not sure about the **"I tried to click on the user icon but the profile didn't open on android and didn't open on ios**", Do you want to click on avatar from settings and open up user-detail modal? I think we dont need that as avatar is in edit mode their and only represents a picture preview. 
let me know what you think of it.

**Comment by 2byrds** [comment]
Looks good in iPhone 
image
Looks good on android
image

**Comment by 2byrds** [comment]
@HunnySajid I'm not sure how to test the pin protection.

**Comment by HunnySajid** [comment]
> @HunnySajid I'm not sure how to test the pin protection.

@2byrds currently it is not protected by pin, I can make it to do so. 
Then, once app is protected by pin and user returns to app after closing it, he would have to enter pin instead of landing on the relationship detail screen. 
I can use the same auth flow for that.

**Comment by HunnySajid** [comment]
> @HunnySajid I'm not sure how to test the pin protection.

I have created a separate task for that.
https://github.com/roots-id/roots-react-native/issues/27
 Do add anything if you want. And if rest is good then we can merge this PR.

**Comment by 2byrds** [comment]
> > @HunnySajid I'm not sure how to test the pin protection.
> 
> I have created a separate task for that. #27 Do add anything if you want. And if rest is good then we can merge this PR.

sounds like a good plan.  the pin protection is low priority right now.  so lets leave that as an open issue for after the Dec demo.

**Review by 2byrds — APPROVED** [review]

**Pull request merged**
