### PR TITLE
WIP: Revamp Screens 

### PR DESCRIPTION
**Pull request by HunnySajid**
Work In Progress:
Credentials Details / Relationship Detail popup content
Settings Screen
Gifted Chat Buttons

https://user-images.githubusercontent.com/19255438/208125975-b5851da9-c803-4cff-a75c-bd7b2cb00bf9.mov

### CODE REVIEW

**Comment by HunnySajid** [comment]
@AlexAndrei98 @2byrds  this is the progress so far. I am still working on some screens.

**Comment by 2byrds** [comment]
Thank you so much for posting @HunnySajid this was very helpful for the meeting.
Here are the notes from watching the video with Ilona and Alex:
Highest priority:
Remove the pink background using the same background as the screen.
Divide the rows by a line at the bottom of each row
Make the key/label bold to distingquish it from value
image

Medium Priority:
Please put the RootsID logo in the top left corner of the Contacts and Credentials screen so that brand is part of our demo coming up.

Lower priority:
We love the 'card look' of the layers of screens (as the slide up), perhaps even the qrcode modal could slide from the bottom and the user can slide it back down when they are done with it?  In general we want to move consistently towards cards on top of cards and dismissing them the same way throughout the app
We'll work on the Settings Screen issues in 2023.

**Comment by 2byrds** [comment]
I've merged these changes into my separate repo by hand (roots-react-native-experimental) which has no expo, newer versions of libs, etc.  I'm going to rebase and merge these changes now, so that your future changes are easier for me to add in the future

**Comment by 2byrds** [comment]
@HunnySajid after merging your work, i'm continuing to update things in my repo, for instance 
image

What would really be helpful for me this weekend is if you can you focus on updating the quick replies to use yellow instead of blue and to possibly not have to click confirm after selecting a button?  And possibly if the buttons could be single selection (radio) instead of being able to multi-select them.... and if you could make the button unselect after touching it, meaning you touch it, it does the action and then unselects.
That would be awesome!

**Comment by HunnySajid** [comment]
@2byrds  Good work with the integration and credentials detail modal. I am going to work on the quick replies thing you mentioned. I will let you know as soon as I am done and then I can help you with the pending tasks if any.

**Comment by 2byrds** [comment]
@HunnySajid perfect thank you!

**Pull request merged**
